[project]
name = "schema-based-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.33.0",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1",
    "streamlit>=1.50.0",
]
